{
 "title": "Main dashboard",
 "time": { "from": "2022-11-06T21:52:54.685Z", "to": "2022-11-06T21:53:21.562Z" },
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-node" },
   {
    "name": "container",
    "query": "tp-1-node-1, tp-1-node-2, tp-1-node-3, tp-1-node-4, tp-1-cadvisor-1, tp-1-grafana-1, tp-1-graphite-1, nginx, bbox"
   }
  ]
 },
 "panels": [
  {
   "title": "Async Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "alias(stats.timers.async-latency.mean, 'mean latency')"
    },
    {
     "target": "alias(stats.timers.async-latency.upper, 'max latency')"
    }
   ]
  },
  {
   "title": "Intensivo Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "alias(stats.timers.intensivo-latency.mean, 'mean latency')"
    },
    {
     "target": "alias(stats.timers.intensivo-latency.upper, 'max latency')"
    }
   ]
  },
  {
   "title": "Bbox 0 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "target": "alias(stats.timers.bbox-0-latency.mean, 'mean latency')"
    },
    {
     "target": "alias(stats.timers.bbox-0-latency.upper, 'max latency')"
    }
   ]
  },
  {
   "title": "Bbox 1 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "alias(stats.timers.bbox-1-latency.mean, 'mean latency')"
    },
    {
     "target": "alias(stats.timers.bbox-1-latency.upper, 'max latency')"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "target": "alias(stats.timers.ping-latency.mean, 'mean latency')"
    },
    {
     "target": "alias(stats.timers.ping-latency.upper, 'max latency')"
    }
   ]
  },
  {
   "title": "Scenarios Counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioCounts.*, 'Scenarios Counts')"
    }
   ]
  },
  {
   "title": "Artillery Error TIMEDOUT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.artillery-node.errors.ETIMEDOUT, 'TIMEDOUT')"
    }
   ]
  },
  {
   "title": "Server Error Address in Use",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.errors.EADDRINUSE, 'Address in Use')"
    }
   ]
  },
  {
   "title": "Scenarios Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.codes.200, 'Scenarios Completed')"
    }
   ]
  },
  {
   "title": "Server Error TimedOut",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.errors.ETIMEDOUT, 'TIMEOUT')"
    }
   ]
  },
  {
   "title": "Artillery Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.latency.min, 'Min Latency')"
    },
    {
     "target": "alias(stats.gauges.$server.latency.max, 'Max Latency')"
    },
    {
     "target": "alias(stats.gauges.$server.latency.median, 'Mean Latency')"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "target": "alias(stats.gauges.$server.rps.count, 'RPS Count')"
    },
    {
     "target": "alias(stats.gauges.$server.rps.mean, 'RPS Mean')"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.$server.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.$server.requestsCompleted, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.$server.pendingRequests, 'Pending')"
    }
   ]
  },
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.$server.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.$server.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.$container.memory_working_set, 6442450944), 'Memory')"
    },
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.$container.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    }
   ]
  }
 ]
}